import test from 'node:test';
import assert from 'node:assert/strict';
import { PGlite } from '@electric-sql/pglite';
import { pg_trgm } from '@electric-sql/pglite/contrib/pg_trgm';
import { applyMigrations } from '../lib/migrations.js';
import { slugify } from '../lib/seo-slugs.js';
import { initialHotels } from '../src/data/mockData.js';
import { buildCatalogQuery, createRepository } from '../lib/repository.js';

test('PostgreSQL schema migrates, rejects invalid relations and enforces versioned writes', async () => {
  const db=new PGlite({extensions:{pg_trgm}});
  const client={ query:async(sql,values)=>values?db.query(sql,values):((await db.exec(sql)).at(-1)||{rows:[]}) };
  const pool={...client,connect:async()=>({...client,release(){}})};
  try {
    await applyMigrations(client);
    await applyMigrations(client);
    const repo=createRepository(pool);
    for(const name of ["Çeşme'de Château Ölüdeniz",'İstanbul IĞDIR','L’hôtel & Café','Muğla ŞİLE']) assert.equal((await db.query('SELECT private.slug($1) AS slug',[name])).rows[0].slug,slugify(name));
    const input={name:'Test Vet',city:'Istanbul',district:'Kadikoy',imageUrl:'',address:'Test',features:[],description:'Test',baseTrustScore:8,lastVerified:'2026-09-04'};
    const vet=await repo.save('vets',input);
    assert.equal(vet.version,1);
    assert.equal((await repo.page('vets')).data.length,1);
    const updated=await repo.save('vets',{id:vet.id,version:vet.version,name:'Updated'});
    assert.equal(updated.version,2);
    await assert.rejects(repo.save('vets',{id:vet.id,version:1,name:'Stale'}),error=>error.status===409);
    const review=await repo.submit('reviews',{targetId:vet.id,author:'Test',text:'Review',rating:8});
    assert.equal(review.status,'pending');
    assert.equal((await repo.feedbackPage('reviews',{targetId:vet.id})).data.length,0);
    await repo.moderate('reviews',review.id,'approved',1);
    assert.equal((await repo.feedbackPage('reviews',{targetId:vet.id})).data.length,1);
    await assert.rejects(repo.remove('vets',vet.id,2),error=>['23001','23503'].includes(error.code));
    await assert.rejects(repo.submit('reviews',{targetId:'missing',author:'Test',text:'Review',rating:8}),error=>error.code==='23503');
    await assert.rejects(repo.submit('reviews',{id:review.id,status:'approved',targetId:vet.id,author:'Test',text:'Hijack',rating:1}));
    const allowed=await db.query("SELECT relrowsecurity FROM pg_class WHERE oid='public.reviews'::regclass");
    assert.equal(allowed.rows[0].relrowsecurity,true);
    const cursorRows=await db.query("INSERT INTO public.vets(id,name,city,district,image_url,address,features,description,base_trust_score,verification_note,created_at) SELECT 'cursor-'||n,'Cursor '||n,'Istanbul','Kadikoy','','Test','[]','Test',8,'', '2026-09-05 00:00:00.123000+00'::timestamptz+n*interval '1 microsecond' FROM generate_series(1,5) n RETURNING id");
    let nextCursor,seen=[];
    do {
      const batch=await repo.page('vets',{limit:2,...(nextCursor?{cursor:nextCursor}:{})});
      seen.push(...batch.data.map(r=>r.id));nextCursor=batch.nextCursor;
    } while(nextCursor);
    assert.equal(seen.length,6);assert.equal(new Set(seen).size,6);
    assert.equal((await repo.page('vets',{q:'cursor'})).data.length,5);
    assert.equal((await repo.page('vets',{q:"'; DELETE FROM vets; --"})).data.length,0);
    assert.throws(()=>buildCatalogQuery('vets',{limit:1000}));
    assert.throws(()=>buildCatalogQuery('vets',{cursor:'invalid'}));
    await assert.rejects(repo.save('vets',{...input,features:{invalid:true}}),error=>error.status===400);
    for(let n=0;n<10;n++)await repo.consumeLimit('local-test-hash');
    await assert.rejects(repo.consumeLimit('local-test-hash'),error=>error.status===429);
    const hotel=await repo.save('hotels',{...initialHotels[0],id:undefined,version:undefined});
    const duplicate=await repo.save('hotels',{...initialHotels[0],name:initialHotels[0].name+' Imported Duplicate',id:undefined,version:undefined});
    const complaint=await repo.submit('complaints',{targetId:duplicate.id,targetName:'Forged',author:'Test',text:'Test'});
    const correction=await repo.submit('corrections',{hotelId:duplicate.id,hotelName:'Forged',text:'Test'});
    const stored=await repo.feedbackPage('complaints',{targetId:duplicate.id},true);
    assert.equal(stored.data[0].targetName,duplicate.name);
    const userA='00000000-0000-4000-8000-000000000001',userB='00000000-0000-4000-8000-000000000002';
    await db.query("INSERT INTO profiles(id,display_name) VALUES($1,'A'),($2,'B')",[userA,userB]);
    await repo.favorite(userA,hotel.id);
    await repo.favorite(userA,duplicate.id);
    await repo.favorite(userB,duplicate.id);
    await db.exec('SET ROLE pati_api');
    await repo.favorite(userA,vet.id);
    assert.equal((await repo.favorites(userA)).data.length,3);
    assert.equal((await repo.favorites(userB)).data.length,1);
    assert.equal((await db.query('SELECT place_id FROM favorites')).rows.length,0,'RLS denies without subject');
    await assert.rejects(db.query("INSERT INTO favorites(user_id,place_id) VALUES($1,$2)",[userB,vet.id]),error=>error.code==='42501');
    await repo.mergeHotels({keeperId:hotel.id,duplicateId:duplicate.id,keeperVersion:hotel.version,duplicateVersion:duplicate.version});
    assert.equal(await repo.one('hotels',duplicate.id),null);
    assert.equal((await repo.favorites(userA)).data.length,2);
    assert.equal((await repo.favorites(userB)).data[0].id,hotel.id);
    assert.equal((await repo.feedbackPage('corrections',{targetId:hotel.id},true)).data[0].id,correction.id);
    await assert.rejects(repo.mergeHotels({keeperId:hotel.id,duplicateId:hotel.id,keeperVersion:1,duplicateVersion:1}));
    await assert.rejects(db.query('SELECT checksum FROM private.app_migrations'),error=>error.code==='42501');
    await db.exec('RESET ROLE; CREATE ROLE anon NOLOGIN; SET ROLE anon');
    await assert.rejects(db.query('SELECT id FROM public.reviews'),error=>error.code==='42501');
    await assert.rejects(db.query("SELECT private.merge_favorites('a','b')"),error=>error.code==='42501');
    await db.exec('RESET ROLE');
    const role=await db.query("SELECT rolbypassrls,rolsuper FROM pg_roles WHERE rolname='pati_api'");
    assert.deepEqual(role.rows[0],{rolbypassrls:false,rolsuper:false});
  } finally {await db.close();}
});
